name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:run

      - name: Build
        run: npm run build
